// Seed data. Geek merch, same spirit as the original vulnerable-node catalog.
// Long copy on purpose: product pages must read like a real store.

const products = [
  {
    name: "Mechanical Keyboard MK-ULTRA",
    description: "Blue switches loud enough to be heard in the standup next door. PBT keycaps, USB-C, hot-swap, and a deliberate absence of RGB because RGB is for other people.",
    long_description: "The MK-ULTRA is our loudest board yet. Lubed blue switches rated for 100 million keystrokes — enough to outlast your patience and everyone else's. Double-shot PBT keycaps with dye-sub legends that will never fade, a south-facing LED budget we spent on a satisfying thock instead. Hot-swap sockets, QMK/VIA support, and a braided USB-C cable long enough to reach the router and back. Warning: your cat will hate it, your colleagues will learn your typing rhythm by heart.",
    price_cents: 12900,
    image: "keyboard.svg",
    stock: 14,
    category: "keyboards",
    featured: true,
    tags: ["hardware", "keyboards", "loud"],
  },
  {
    name: "Rubber Duck Pro",
    description: "Premium desk duck for rubber-duck debugging. Floats in coffee by accident. Explains your bug by saying nothing.",
    long_description: "Every serious engineer owns a duck; the pros own this one. Molded from high-density vinyl with a weighted base so it never tips over mid-explanation, the Rubber Duck Pro features a gaze engineered to induce exactly the right amount of guilt. Float tests passed (accidentally, in coffee). Works offline. No drivers required. The classic debugging companion: explain your code line by line and hear the bug reveal itself in the silence between quacks.",
    price_cents: 999,
    image: "duck.svg",
    stock: 87,
    category: "desk",
    featured: true,
    tags: ["desk", "debugging", "gift"],
  },
  {
    name: "Segfault Mug",
    description: "Ceramic mug, 350ml. Prints 'Segmentation fault (core dumped)' on the bottom so you find out after the last sip.",
    long_description: "Dishwasher-safe, microwave-safe, production-safe (we make no promises). The Segfault Mug keeps 350ml of your preferred compile fuel at temperature while the message on the bottom delivers its punchline only to those who finish their coffee — a daily lesson in reading error messages to the very end. Double-fired glaze, reinforced handle for keyboard-adjacent placement, and a base that leaves a satisfying core dump on white desks.",
    price_cents: 1400,
    image: "mug.svg",
    stock: 42,
    category: "desk",
    featured: false,
    tags: ["desk", "cups", "gift"],
  },
  {
    name: "Cable Spaghetti 5kg",
    description: "Five kilograms of assorted USB, HDMI and mystery cables. Every box is a surprise. No returns, obviously.",
    long_description: "Somewhere in this box is the exact cable you need. It is not labeled. Our warehouse team (a conveyor belt with opinions) gathers retired demo cables, factory seconds and one extremely rare VGA-to-FireWire adapter into five-kilogram boxes of pure potential. Great for cable management practice, art projects, and that drawer every household is legally required to have. Sold by weight, not by destiny.",
    price_cents: 2500,
    image: "cables.svg",
    stock: 23,
    category: "hardware",
    featured: false,
    tags: ["hardware", "cables", "chaos"],
  },
  {
    name: "Sticker Pack: Hexadecimal",
    description: "40 vinyl stickers: 0x00 to 0x27 plus bonus 0xCAFEBABE. Weatherproof, laptop-approved.",
    long_description: "Your laptop is a resume; dress it accordingly. Forty die-cut vinyl stickers counting from 0x00 to 0x27, plus the legendary 0xCAFEBABE for special occasions. UV-laminated, dishwasher-tested (on water bottles, not laptops), and sized to fit keyboard gaps, monitor bezels, and the back of your phone. Cover every warranty sticker you have ever ignored.",
    price_cents: 800,
    image: "stickers.svg",
    stock: 130,
    category: "stickers",
    featured: false,
    tags: ["stickers", "gift", "cheap"],
  },
  {
    name: "LED Badge of Shame",
    description: "Programmable LED badge. Preloaded text: 'it works on my machine'. USB rechargeable.",
    long_description: "Why explain your production incident when your chest can do it for you? The LED Badge of Shame scrolls up to 512 characters of pure confession in 8-bit pixel glory. Preloaded with 'it works on my machine', reprogrammable over USB-C to display your true feelings: 'RTFM', 'have you tried restarting?', or the evergreen 'deploying on Friday'. 12-hour battery, magnetic back, conference-approved.",
    price_cents: 1900,
    image: "badge.svg",
    stock: 55,
    category: "wearables",
    featured: true,
    tags: ["hardware", "wearables", "gag"],
  },
  {
    name: "The USB Rocket",
    description: "USB-powered desk rocket. Functionality: none. Usability: none. The best choice!",
    long_description: "A classic returns. The USB Rocket does nothing, brilliantly. Plug it in: its nose glows. Press the button: it vibrates with ambition. It has never flown and it never will, and that is precisely the point — a monument to every side project you have ever abandoned at 80% completion. Hand-painted finishes vary; disappointment is uniform.",
    price_cents: 2200,
    image: "rocket.svg",
    stock: 18,
    category: "classic",
    featured: false,
    tags: ["hardware", "gag", "classic"],
  },
  {
    name: "Potty Putter",
    description: "The game for the avid golfers. Practice your putt where you spend your best thinking time.",
    long_description: "Architecture decisions happen in one room and one room only. The Potty Putter turns that room into a driving range: felt-green putting mat with rail returns, regulation-size hole, two golf balls, one putter, and a flag that reads 'SHIPPING NOW'. Fits standard toilets. The average user cuts four strokes per sprint and every single one of them tells the same joke. We are sorry. We are not sorry.",
    price_cents: 2000,
    image: "putter.svg",
    stock: 31,
    category: "classic",
    featured: false,
    tags: ["gag", "bathroom", "classic"],
  },
  {
    name: "Phone Fingers",
    description: "Phone fingers work perfectly with touchscreens and prevent fingerprints and smudges. 20 disposable caps.",
    long_description: "Why wash your hands when you can armor them? Phone Fingers are disposable latex caps shaped like fingertips, engineered for flawless capacitive contact. Twenty caps per box — one week of smudge-free doomscrolling. Invented in 2009, perfected by nobody, revived by us because nostalgia is a business model. Also great for counting in binary on one hand.",
    price_cents: 300,
    image: "phonefingers.svg",
    stock: 210,
    category: "classic",
    featured: false,
    tags: ["gag", "classic", "cheap"],
  },
  {
    name: "Daddle",
    description: "Be the best father with Daddle: dad's saddle for horsing around. Weight limit: one (1) small child.",
    long_description: "The award nobody asked for: Best Product at the 2011 Baby Innovation Fair (real, look it up). The Daddle is a padded saddle that straps to dad and turns 'horsey time' into a 45-minute endurance sport. Machine-washable cover, reinforced grip handles, ergonomic withers. Weight limit: one (1) small child or two (2) cats. Warning: child will demand 'again' until your spine files for divorce.",
    price_cents: 4900,
    image: "daddle.svg",
    stock: 9,
    category: "classic",
    featured: false,
    tags: ["gag", "classic", "parenting"],
  },
  {
    name: "Walker Watermelons",
    description: "Take a walk with your watermelons and make them feel comfortable. Leash included, watermelon not.",
    long_description: "Fruit deserves fresh air too. The Walker Watermelons kit includes an adjustable harness (small and XL neck sizes) and a 1.2m leash engineered for melons up to 8kg. Take yours to the park, the farmers market, or — for advanced users — the beach, where it can look at the ocean it came from. Watermelon not included; melon anxiety not covered by warranty.",
    price_cents: 1500,
    image: "watermelon.svg",
    stock: 26,
    category: "classic",
    featured: false,
    tags: ["gag", "classic", "summer"],
  },
  {
    name: "HD Vision",
    description: "Reality is not enough for you? Improve your life with the HD vision glasses. Colors pop, disappointment guaranteed.",
    long_description: "The world looks better through tinted plastic and we have the science to prove nothing. HD Vision glasses enhance contrast, deepen blues, and make sunsets 340% more Instagram-ready (our marketing team's estimate). One size fits all heads, two lenses fit one face. Warning: does not include actual HD. Side effects may include smugness at traffic lights.",
    price_cents: 600,
    image: "glasses.svg",
    stock: 74,
    category: "classic",
    featured: false,
    tags: ["gag", "classic", "cheap"],
  },
];

const users = [
  { username: "alice",  password: "alice123",  email: "alice@example.com",  role: "customer" },
  { username: "bob",    password: "bob123",    email: "bob@example.com",    role: "customer" },
  { username: "admin",  password: "admin123",  email: "admin@nodebazaar.local", role: "admin" },
];

module.exports = { products, users };